#!/bin/bash

# check logs for errors

EMAIL=root
HOSTNAME=`hostname -s`

send_file() {
  FILE=$1
  SUBJECT=$2
  if [ ! -z "`head $FILE`" ] ; then
    cat "$FILE" | mail -s "$HOSTNAME: $SUBJECT" $EMAIL > /dev/null
  fi
}


# Apache logs

IGNORE='w00tw00t.at.ISC.SANS'
for F in `ls /var/log/apache2/*error.log` ; do
  /usr/sbin/logtail -f$F -o$F.offset-errors | egrep '\[(emerg|alert|crit)\]' | egrep -v "$IGNORE" > /tmp/apache_errors
  send_file /tmp/apache_errors "Apache errors: $F"
done


# App log
# NOTE: this assumes that the rails app is using the log format defined by
# https://github.com/pauldowman/better_logging
DELIMITER='s/^--/\n\n------------------------------------------------------------------------------------------\n\n/'
PATTERN='^[0-9a-zA-Z.-]+ +\d{4}-\d{2}-\d{2}T\S+ +(ERROR|FATAL|UNKNOWN) +'
for F in `ls /srv/*/shared/log/*.log` ; do
  /usr/sbin/logtail -f$F -o$F.offset-errors | egrep -C 15 "$PATTERN" | sed $DELIMITER > /tmp/app_errors
  send_file /tmp/app_errors "App errors: $F"
done

